Repository gorilla/csrf, pull requests merged in 2023-07, with the labels that each got.

#166 [GPT-96] Update go version & add verification/testing tools
  .circleci/config.yml
  .editorconfig
  .github/release-drafter.yml
  .github/stale.yml
  .github/workflows/issues.yml
  .github/workflows/test.yml
  .gitignore
  AUTHORS
  Makefile
  README.md
  context.go
  csrf.go
  csrf_test.go
  go.mod
  helpers.go
  helpers_test.go
  store_test.go
  vendor/github.com/gorilla/securecookie/.travis.yml
  vendor/github.com/gorilla/securecookie/LICENSE
  vendor/github.com/gorilla/securecookie/README.md
  vendor/github.com/gorilla/securecookie/doc.go
  vendor/github.com/gorilla/securecookie/fuzz.go
  vendor/github.com/gorilla/securecookie/securecookie.go
  vendor/modules.txt
Labels: size/L

#167 updated licence
  LICENSE
Labels: size/M

#168 Update issues.yml
  .github/workflows/issues.yml
Labels: size/XS
